name: library
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Alexei Eleusis Díaz Vera <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  meta: "^1.1.2"
  shuttlecock: "^0.4.1"

dev_dependencies:
  test: ^0.12.0
